# Generated by Django 4.2.3 on 2023-07-21 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("question", models.CharField(max_length=256)),
                (
                    "quiz_type",
                    models.CharField(
                        choices=[("SELECTIVE", "Selective"), ("STATE", "State")],
                        default="SELECTIVE",
                        max_length=20,
                    ),
                ),
                ("state_question_answer", models.CharField(max_length=24)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QuizOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("content", models.CharField(max_length=100)),
                ("is_answer", models.BooleanField(default=False)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.quiz"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
